### ISSUE TITLE
Release To Do

### ISSUE THREAD

**Issue by Morpheus1101** [Morpheus1101/Arduous-Lost-Wasteland#1]
- [x] Check https://github.com/iChun/iChunUtil/issues/169 has been fixed
- [x] Check Mineralogy works with all the things
- [x] Think of a good description for pack
- [x] Get images for pack

**Comment by iChun** [comment]
https://github.com/iChun/iChunUtil/issues/169 was a Forge bug that was fixed in Forge 2624
